### ISSUE TITLE
Extension is not compatible with new version of ULauncher

### ISSUE THREAD

**Issue by papermache** [manulaiko/ulauncher-openInBrowser#3]
Linux version: Linux 4.15.0-48-generic 
ULauncher v5.3.0~beta1 
Extension API v2.0.0 

![image](https://user-images.githubusercontent.com/2126012/59811015-f3f32b80-92d5-11e9-9e2b-93601b29775a.png)

**Comment by Innercode** [comment]
https://github.com/manulaiko/ulauncher-openInBrowser/pull/4

**Comment by manulaiko** [comment]
My fault, I should've specified in the readme that this repo is no longer maintained.

If anyone is willing to fork and maintain their version, I'm more than happy to link to the repo in the readme file.

**Comment by Innercode** [comment]
No problem. But let them fork my repo at https://github.com/Innercode/ulauncher-openInBrowser which supports v5.
I don't have any knowledge of Python. The upgrade was just simple enough. 
To anyone, feel free to fork and maintain it and submit it to the extension page.

**Comment by manulaiko** [comment]
Okay, I'll add your repo to the readme. Thanks.
